import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import classNames from 'classnames/bind';
import { useTranslation } from 'react-i18next';
import { BankIcon } from '@assets/icons/BankIcon';
import { HandCoinsIcon } from '@assets/icons/HandCoinsIcon';
import { HandPointingIcon } from '@assets/icons/HandPointingIcon';
import { LightningIcon } from '@assets/icons/LightningIcon';
import { PlusMinusIcon } from '@assets/icons/PlusMinusIcon';
import { ShieldCheckIcon } from '@assets/icons/ShieldCheckIcon';
import { TargetIcon } from '@assets/icons/TargetIcon';
import { Container } from '@src/components/ui/Container';
import { FeatureCard } from '@src/components/ui/FeatureCard';
import styles from './about.module.scss';
const cx = classNames.bind(styles);
const About = () => {
    const { t, i18n } = useTranslation();
    i18n.language = i18n.language?.split('-')[0];
    return (_jsx(Container, { children: _jsxs("div", { className: cx('about'), children: [_jsx("h1", { className: cx('about-title'), children: t('about_title') }), _jsxs("div", { className: cx('about-desc'), children: [t('about_desc'), _jsxs("svg", { width: "252", height: "130", viewBox: "0 0 252 130", fill: "none", className: cx('about-desc__vector'), xmlns: "http://www.w3.org/2000/svg", children: [_jsx("path", { d: "M450.758 -104.45L57.4961 229.744L-0.003336 229.745L266.941 -104.452L450.758 -104.45Z", fill: "#FBE54D" }), _jsx("path", { d: "M492.345 7.78879L167.15 213.402L117.803 213.402L537.016 -132.557L492.345 7.78879Z", fill: "#FBE54D" })] })] }), _jsxs("div", { className: cx('about-how'), children: [_jsx("h2", { className: cx('about-how-it-work'), children: t('about_how_it_work') }), _jsxs("div", { className: cx('about-how__wrapper'), children: [_jsxs("div", { className: cx('about-how__wrapper-text'), children: [t('about_how_it_work_text'), _jsx("span", { className: cx('bankimonline'), children: t('bankimonline') }), t('about_how_it_work_text_second')] }), _jsx("div", { className: cx('about-how__wrapper-img'), children: _jsx("img", { src: "/static/about/frame-1410093763@3x.png", alt: "" }) })] })] }), _jsxs("div", { className: cx('about-why'), children: [_jsx("h2", { className: cx('about-why__title'), children: t('about_why_title') }), _jsxs("div", { className: cx('about-why__cards'), children: [_jsx(FeatureCard, { icon: _jsx(PlusMinusIcon, {}), title: t('about_why_solve_problem_title'), text: t('about_why_solve_problem') }), _jsx(FeatureCard, { icon: _jsx(BankIcon, {}), title: t('about_why_bank_title'), text: t('about_why_bank') }), _jsx(FeatureCard, { icon: _jsx(LightningIcon, {}), title: t('about_why_mortgage_complete_title'), text: t('about_why_mortgage_complete') }), _jsx(FeatureCard, { icon: _jsx(HandPointingIcon, {}), title: t('about_why_simple_title'), text: t('about_why_simple') }), _jsx(FeatureCard, { icon: _jsx(HandCoinsIcon, {}), title: t('about_why_credit_title'), text: t('about_why_credit') }), _jsx(FeatureCard, { icon: _jsx(ShieldCheckIcon, { size: 32, color: "#fff" }), title: t('about_why_security_title'), text: t('about_why_security') }), _jsx(FeatureCard, { icon: _jsx(TargetIcon, {}), title: t('about_why_fast_title'), text: t('about_why_fast'), size: "full" })] })] })] }) }));
};
export default About;
