version: '3.8'

services:
    node:
      build: .
      ports:
        - "3000:3000"
      volumes:
        - .:/usr/src/app
        - ./node_modules:/usr/src/app/node_modules
      command: npm start
      networks:
        - network

networks:
  network:
    driver: bridge
