[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'cd mainapp && npm install && npm run build && cd ..'
]

[start]
cmd = 'node server-db.js' 