name: QA Protection
# WHAT THIS DOES:
# 1. Runs when you push to GitHub (not locally - no delay!)
# 2. Prevents BAD CODE from merging to main branch
# 3. Runs heavy tests that would slow your local machine
# 4. Alerts team if something breaks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Quick checks (2-3 seconds)
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 🚀 Quick Syntax Check
        run: |
          # Just check if code compiles - super fast!
          npm ci --ignore-scripts
          npm run build --if-present
        continue-on-error: false # Blocks merge if build fails
  
  # Run heavy tests in GitHub's cloud (not your machine!)
  heavy-tests:
    runs-on: ubuntu-latest
    needs: quick-check
    steps:
      - uses: actions/checkout@v3
      
      - name: 🧪 Run All Tests (in GitHub's servers)
        run: |
          # These run on GitHub - not slowing YOUR computer!
          npm ci
          npm test
          
      - name: 📊 Check Coverage
        run: |
          npm run test:coverage
          # Fail if coverage drops below 70%
          npx nyc check-coverage --lines 70
  
  # BENEFIT: Prevents broken code from reaching production
  block-if-failed:
    runs-on: ubuntu-latest
    needs: [quick-check, heavy-tests]
    if: failure()
    steps:
      - name: 🚫 Block Merge
        run: |
          echo "Tests failed! Fix before merging."
          exit 1
          
      - name: 📧 Alert Team (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Send Slack/email alert about failed tests
          echo "Alert: Tests failing on main branch!"

# BENEFITS SUMMARY:
# ✅ Runs tests on GitHub's servers (not your machine)
# ✅ Blocks bad code from main branch
# ✅ No local performance impact
# ✅ Team gets alerts for problems
# ✅ Free with GitHub (2000 minutes/month)