import { jsx as _jsx } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import { I18nextProvider } from 'react-i18next';
import { Provider } from 'react-redux';
import App from './app/App.tsx';
import './index.scss';
import { store } from './store';
import i18n from './utils/i18n';
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _jsx(I18nextProvider, { i18n: i18n, children: _jsx(Provider, { store: store, children: _jsx(App, {}) }) }) }));
