[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['rm -rf node_modules package-lock.json && npm install']

[phases.build]
cmds = [
  'cd frontend',
  'rm -rf node_modules package-lock.json',
  'npm install',
  'npm run build',
  'cd ..'
]

[start]
cmd = 'node server.js' 